"""Accés a dades compatible amb PostgreSQL i SQLite local."""

import os
import re
import sqlite3
from pathlib import Path

import pandas as pd
import streamlit as st

try:
    import psycopg
except ImportError:  # Permet continuar treballant en local abans d'instal·lar-lo.
    psycopg = None


APP_DIR = Path(__file__).resolve().parent
SQLITE_FILE = Path(
    os.environ.get("GESTIO_BUS_SQLITE_FILE", APP_DIR / "gestio_autobusos.db")
)
PATRO_MATRICULA = r"\d{4}[B-DF-HJ-NPR-TV-Z]{3}"


def matricula_valida(matricula):
    """Comprova el format de matrícula utilitzat per l'aplicació."""
    if not isinstance(matricula, str):
        return False
    return bool(re.fullmatch(PATRO_MATRICULA, matricula.strip().upper()))


def _load_database_url():
    """Llegeix la connexió externa sense exposar-la al codi font."""
    env_url = os.environ.get("DATABASE_URL", "").strip()
    if env_url:
        return env_url

    try:
        return str(st.secrets.get("DATABASE_URL", "")).strip()
    except FileNotFoundError:
        return ""


DATABASE_URL = _load_database_url()
DATABASE_BACKEND = "postgresql" if DATABASE_URL else "sqlite"
DATABASE_INTEGRITY_ERRORS = (sqlite3.IntegrityError,)
if psycopg is not None:
    DATABASE_INTEGRITY_ERRORS += (psycopg.IntegrityError,)


class DatabaseCursor:
    """Adapta els paràmetres SQLite (`?`) al format de PostgreSQL."""

    def __init__(self, cursor, backend):
        self._cursor = cursor
        self._backend = backend

    @property
    def description(self):
        return self._cursor.description

    def execute(self, query, params=()):
        if self._backend == "postgresql":
            query = query.replace("?", "%s")
        self._cursor.execute(query, params)
        return self

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def close(self):
        self._cursor.close()


class DatabaseConnection:
    """Interfície comuna per a connexions SQLite i PostgreSQL."""

    def __init__(self, connection, backend):
        self._connection = connection
        self.backend = backend

    def cursor(self):
        return DatabaseCursor(self._connection.cursor(), self.backend)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def get_db_connection():
    """Obre PostgreSQL al núvol o la base SQLite quan es treballa en local."""
    if DATABASE_BACKEND == "postgresql":
        if psycopg is None:
            raise RuntimeError(
                "Falta la dependència psycopg per connectar amb PostgreSQL."
            )
        connection = psycopg.connect(DATABASE_URL, connect_timeout=15)
        return DatabaseConnection(connection, DATABASE_BACKEND)

    connection = sqlite3.connect(SQLITE_FILE, timeout=30)
    connection.execute("PRAGMA busy_timeout = 30000")
    connection.execute("PRAGMA synchronous = NORMAL")
    return DatabaseConnection(connection, DATABASE_BACKEND)


@st.cache_data(ttl=5, show_spinner=False)
def vehicles_esperant():
    """Retorna el comptador lateral sense repetir la consulta en cada rerun."""
    conn = get_db_connection()
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT COUNT(*) FROM registres WHERE estat = 'Esperant'")
        return cursor.fetchone()[0]
    finally:
        conn.close()


def calcular_sentit(estacio):
    """Calcula el sentit segons l'estació de sortida."""
    if estacio == "GR":
        return "Ascendent"
    elif estacio == "SR":
        return "Descendent"
    return None


def init_db():
    """Crea l'esquema necessari sense esborrar dades existents."""
    id_definition = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if DATABASE_BACKEND == "postgresql"
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    conn = get_db_connection()
    try:
        if DATABASE_BACKEND == "sqlite":
            conn._connection.execute("PRAGMA journal_mode = WAL")

        cursor = conn.cursor()
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS autocars (
                matricula TEXT PRIMARY KEY,
                capacitat INTEGER,
                acces_pmr TEXT,
                aire_acondicionat TEXT,
                conductor TEXT
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS registres (
                id {id_definition},
                matricula TEXT NOT NULL,
                hora_entrada TEXT NOT NULL,
                hora_sortida TEXT,
                estacio TEXT,
                sentit TEXT,
                estat TEXT NOT NULL
            )
        """)
        
        # Completar esquemes antics sense provocar errors de columna duplicada.
        # A PostgreSQL, capturar un error d'ALTER TABLE sense fer rollback deixa
        # tota la transacció invalidada; IF NOT EXISTS evita aquesta situació.
        if DATABASE_BACKEND == "postgresql":
            cursor.execute(
                "ALTER TABLE registres ADD COLUMN IF NOT EXISTS estacio TEXT"
            )
            cursor.execute(
                "ALTER TABLE registres ADD COLUMN IF NOT EXISTS sentit TEXT"
            )
        else:
            cursor.execute("PRAGMA table_info(registres)")
            columnes = {fila[1] for fila in cursor.fetchall()}
            if "estacio" not in columnes:
                cursor.execute("ALTER TABLE registres ADD COLUMN estacio TEXT")
            if "sentit" not in columnes:
                cursor.execute("ALTER TABLE registres ADD COLUMN sentit TEXT")
        
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def read_dataframe(query, conn, params=()):
    """Executa una consulta i retorna un DataFrame en tots dos motors."""
    cursor = conn.cursor()
    try:
        cursor.execute(query, params)
        columns = [column[0] for column in cursor.description]
        return pd.DataFrame.from_records(cursor.fetchall(), columns=columns)
    finally:
        cursor.close()


def _normalitzar_valor(valor):
    """Converteix valors de pandas en valors comparables i aptes per a SQL."""
    if pd.isna(valor):
        return None
    if hasattr(valor, "item"):
        return valor.item()
    return valor


def analitzar_canvis_dataframe(original, editat, clau, camps):
    """Retorna files afegides, modificades i claus eliminades."""
    originals = {}
    for _, fila in original.iterrows():
        valor_clau = _normalitzar_valor(fila.get(clau))
        if valor_clau is not None:
            originals[valor_clau] = {
                camp: _normalitzar_valor(fila.get(camp)) for camp in camps
            }

    afegides = []
    modificades = []
    claus_editades = set()

    for _, fila in editat.iterrows():
        valor_clau = _normalitzar_valor(fila.get(clau))
        valors = {camp: _normalitzar_valor(fila.get(camp)) for camp in camps}

        if valor_clau is None:
            # Les files buides que crea l'editor no són canvis reals.
            if any(valor not in (None, "") for valor in valors.values()):
                afegides.append({clau: None, **valors})
            continue

        claus_editades.add(valor_clau)
        fila_editada = {clau: valor_clau, **valors}
        if valor_clau not in originals:
            afegides.append(fila_editada)
        elif valors != originals[valor_clau]:
            modificades.append(fila_editada)

    eliminades = [valor for valor in originals if valor not in claus_editades]
    return afegides, modificades, eliminades


def desar_canvis_autocars(afegides, modificades, eliminades):
    """Aplica només els canvis de flota indicats dins d'una transacció."""
    conn = get_db_connection()
    try:
        cursor = conn.cursor()
        for matricula in eliminades:
            cursor.execute("DELETE FROM autocars WHERE matricula = ?", (matricula,))

        for fila in modificades:
            matricula = str(fila["matricula"] or "").strip().upper()
            if not matricula_valida(matricula):
                raise ValueError(f"La matrícula {matricula or '(buida)'} no és vàlida.")
            cursor.execute("""
                UPDATE autocars
                SET capacitat = ?, acces_pmr = ?, aire_acondicionat = ?, conductor = ?
                WHERE matricula = ?
            """, (
                int(fila["capacitat"]) if fila["capacitat"] is not None else None,
                fila["acces_pmr"],
                fila["aire_acondicionat"],
                fila["conductor"],
                matricula,
            ))

        for fila in afegides:
            matricula = str(fila["matricula"] or "").strip().upper()
            if not matricula_valida(matricula):
                raise ValueError(f"La matrícula {matricula or '(buida)'} no és vàlida.")
            cursor.execute("""
                INSERT INTO autocars (
                    matricula, capacitat, acces_pmr, aire_acondicionat, conductor
                ) VALUES (?, ?, ?, ?, ?)
            """, (
                matricula,
                int(fila["capacitat"]) if fila["capacitat"] is not None else None,
                fila["acces_pmr"],
                fila["aire_acondicionat"],
                fila["conductor"],
            ))

        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def afegir_autocar(matricula, capacitat, acces_pmr, aire_acondicionat, conductor):
    """Afegeix un únic autocar validat dins d'una transacció."""
    matricula = str(matricula or "").strip().upper()
    if not matricula_valida(matricula):
        raise ValueError("La matrícula ha de tenir 4 xifres i 3 consonants.")

    conn = get_db_connection()
    try:
        cursor = conn.cursor()
        cursor.execute("""
            INSERT INTO autocars (
                matricula, capacitat, acces_pmr, aire_acondicionat, conductor
            ) VALUES (?, ?, ?, ?, ?)
        """, (
            matricula,
            int(capacitat),
            acces_pmr,
            aire_acondicionat,
            conductor,
        ))
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def desar_canvis_registres(afegides, modificades, eliminades):
    """Aplica canvis incrementals als registres sense reconstruir la taula."""
    conn = get_db_connection()
    try:
        cursor = conn.cursor()
        for registre_id in eliminades:
            cursor.execute("DELETE FROM registres WHERE id = ?", (int(registre_id),))

        for fila in modificades:
            estacio = fila["estacio"]
            matricula = str(fila["matricula"] or "").strip().upper()
            if not matricula_valida(matricula):
                raise ValueError(f"La matrícula {matricula or '(buida)'} no és vàlida.")
            cursor.execute("""
                UPDATE registres
                SET matricula = ?, hora_entrada = ?, hora_sortida = ?,
                    estacio = ?, sentit = ?, estat = ?
                WHERE id = ?
            """, (
                matricula,
                fila["hora_entrada"],
                fila["hora_sortida"],
                estacio,
                calcular_sentit(estacio) if estacio else None,
                fila["estat"],
                int(fila["id"]),
            ))

        for fila in afegides:
            estacio = fila["estacio"]
            matricula = str(fila["matricula"] or "").strip().upper()
            if not matricula_valida(matricula):
                raise ValueError(f"La matrícula {matricula or '(buida)'} no és vàlida.")
            cursor.execute("""
                INSERT INTO registres (
                    matricula, hora_entrada, hora_sortida, estacio, sentit, estat
                ) VALUES (?, ?, ?, ?, ?, ?)
            """, (
                matricula,
                fila["hora_entrada"],
                fila["hora_sortida"],
                estacio,
                calcular_sentit(estacio) if estacio else None,
                fila["estat"],
            ))

        sync_registres_sequence(conn)
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def sync_registres_sequence(conn):
    """Sincronitza l'identificador automàtic després d'importar IDs explícits."""
    if DATABASE_BACKEND != "postgresql":
        return

    cursor = conn.cursor()
    try:
        cursor.execute("""
            SELECT setval(
                pg_get_serial_sequence('registres', 'id'),
                COALESCE(MAX(id), 1),
                COUNT(*) > 0
            )
            FROM registres
        """)
    finally:
        cursor.close()


def migrate_sqlite_to_postgres():
    """Copia la base local a PostgreSQL si la destinació encara és buida."""
    if DATABASE_BACKEND != "postgresql":
        raise RuntimeError("Configura DATABASE_URL abans d'executar la migració.")
    if not SQLITE_FILE.exists():
        raise FileNotFoundError(f"No s'ha trobat la base local: {SQLITE_FILE}")

    with sqlite3.connect(SQLITE_FILE) as source:
        autocars = source.execute(
            "SELECT matricula, capacitat, acces_pmr, aire_acondicionat, conductor "
            "FROM autocars"
        ).fetchall()
        registres = source.execute(
            "SELECT id, matricula, hora_entrada, hora_sortida, estacio, sentit, estat FROM registres"
        ).fetchall()

    target = get_db_connection()
    try:
        cursor = target.cursor()
        cursor.execute("SELECT COUNT(*) FROM autocars")
        autocars_existents = cursor.fetchone()[0]
        cursor.execute("SELECT COUNT(*) FROM registres")
        registres_existents = cursor.fetchone()[0]
        if autocars_existents or registres_existents:
            raise RuntimeError(
                "La base PostgreSQL ja conté dades; s'atura la migració per evitar duplicats."
            )

        for row in autocars:
            cursor.execute("""
                INSERT INTO autocars (
                    matricula, capacitat, acces_pmr, aire_acondicionat, conductor
                ) VALUES (?, ?, ?, ?, ?)
            """, row)

        for row in registres:
            cursor.execute("""
                INSERT INTO registres (
                    id, matricula, hora_entrada, hora_sortida, estacio, sentit, estat
                ) VALUES (?, ?, ?, ?, ?, ?, ?)
            """, row)

        sync_registres_sequence(target)
        target.commit()
        return {"autocars": len(autocars), "registres": len(registres)}
    except Exception:
        target.rollback()
        raise
    finally:
        target.close()


def database_status():
    if DATABASE_BACKEND == "postgresql":
        return "PostgreSQL persistent", True
    return "SQLite local", False
